site:
  theme: Copper
  baseUrl: 'https://copper-leaf.github.io/ballast/'
  about:
    siteName: Ballat
    siteDescription: Opinionated Kotlin multiplatform MVI library

theme:
  social:
    other:
      - { link: 'https://github.com/copper-leaf',         label: 'Copper Leaf Home', icon: 'fas fa-home' }
      - { link: 'https://github.com/copper-leaf/ballast', label: 'Github',           icon: 'fab fa-github'}
      - { link: 'https://twitter.com/OrchidSSG',          label: 'Twitter',          icon: 'fab fa-twitter'}
  menu:
    # Main site menu in toolbar
    - { type: 'github', githubProject: 'orchidhq/Orchid'  }
    - type: 'submenu'
      title: 'Copper Leaf'
      menu:
        - { type: 'github', githubProject: 'copper-leaf/common'  }
        - { type: 'github', githubProject: 'copper-leaf/clog'    }
        - { type: 'github', githubProject: 'copper-leaf/kudzu'   }
        - { type: 'github', githubProject: 'copper-leaf/trellis' }
        - { type: 'github', githubProject: 'copper-leaf/thistle' }
        - { type: 'github', githubProject: 'copper-leaf/ballast' }
        - { type: 'github', githubProject: 'copper-leaf/kodiak'  }
        - { type: 'github', githubProject: 'copper-leaf/krow'    }
  sidebarBackground: 'primary'
  sidebarBackgroundType: 'GRADIENT'
  colors:
    purple: '#a2abba'
  palette:
    primary: 'PURPLE'
    link: 'PURPLE'
    linkVisited: 'BLUE'

allPages:
  menu:
    # Menu in left sidebar
    - type: 'page'
      itemId: 'Home'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'wiki'
  layoutConfig:
    wrapPageInBox: true
    wrapTitleInBox: false
    includeTitle: false
    includeBreadcrumbs: false
    pageContentsMenu:
      # Sticky menu on the page
      - type: 'separator'
        title: 'In This Page'
      - type: 'pageIds'
        structure: nested
        maxLevel: 2
  metaComponents:
    - type: "orchidSearch"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy

changelog:
  adapter:
    type: "file"
    baseDir: "./../../../../"

snippets:
  sections:
    - tags: ['embedded_snippets']
      adapter:
        type: 'embedded'
        recursive: true
        baseDirs:
          - './../../../../ballast-core/'

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'copper-leaf/ballast'
        username: 'cjbrooks12'
        commitish: 'main'
      - type: githubPages
        repo: 'copper-leaf/ballast'
        username: 'cjbrooks12'
  generators:
    disabled:
      - 'kotlindoc'
      - 'assets'
